name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 (Checkout)
        uses: actions/checkout@v3

      - name: Step 2 (Engine   )     
        with:
          repository: 'grupoboticario/eventhub-registry-engine'
          ref: 'refs/tags/v1.14.0'
          token: ${{ secrets.GIT_HUB_TOKEN }}
          path: 'engine'
        uses: actions/setup-node@v3
        with:
          node-version: 14
